#!/usr/bin/env python3
"""Second patch: appends extra content to 18 articles still under 2500 words."""
import json, re

def word_count(html):
    stripped = re.sub(r'<[^>]+>', ' ', html)
    stripped = re.sub(r'\s+', ' ', stripped).strip()
    return len(stripped.split()) if stripped else 0

# Keyed by post ID (not slug)
PATCHES = {}

PATCHES['solar-battery-2026'] = """
<h2>Battery Warranty and Degradation: What the Fine Print Says</h2>
<p>Battery warranties are one of the most misunderstood aspects of solar storage purchases. Most manufacturers offer a 10-year performance warranty that guarantees the battery will retain at least 70% of its original capacity. However, what counts as a "cycle" and what voids coverage varies dramatically between brands.</p>
<p>Tesla Powerwall's warranty covers unlimited cycles during the warranty period, provided the battery operates within specified temperature ranges. Sungrow and BYD typically specify a maximum number of cycles — often 6,000 to 10,000 — before the warranty becomes void. For a home cycling the battery daily, 6,000 cycles represents roughly 16 years of use, so this rarely becomes an issue in practice.</p>
<p>Thermal management matters enormously for longevity. Lithium iron phosphate (LFP) chemistry, used by BYD and increasingly by other manufacturers, handles high temperatures better than nickel manganese cobalt (NMC) cells. If you live in Queensland or Western Australia where summers regularly exceed 35°C, LFP chemistry deserves extra weighting in your decision.</p>
<p>Degradation rates affect your return on investment calculations. If a 10 kWh battery degrades to 7 kWh of usable capacity by year 8, your actual bill savings in years 6–10 will be lower than your initial projections. Ask installers for real-world degradation data from installations in your climate zone, not just laboratory specifications.</p>
<h2>Virtual Power Plants: Turning Your Battery Into Extra Income</h2>
<p>Virtual power plants (VPPs) represent an emerging revenue stream for battery owners that most installers don't proactively mention. A VPP aggregates hundreds or thousands of home batteries and coordinates them to respond to grid stress events — essentially functioning as a large power station without any physical plant.</p>
<p>In South Australia, AGL's VPP and Origin's VPP have paid participants hundreds of dollars per year in additional revenue. Energy Locals and Simply Energy also run VPP programs in multiple states. Participation typically requires compatible hardware (not all inverters can receive dispatch signals) and agreement to occasional discharge events that last 15–60 minutes.</p>
<p>The trade-off is reduced personal energy independence during those events. If the grid calls on your battery at 6pm on a hot day and you haven't finished your evening peak demand, you may briefly import grid power. Most VPP operators cap the number of annual dispatch events and compensate participants at above-market rates, making participation financially attractive for most households.</p>
"""

PATCHES['fast-internet-2026'] = """
<h2>Real-World Speed Tests: What Users Actually Experience</h2>
<p>Marketing speeds and real-world speeds diverge considerably on all broadband technologies. ACCC's Measuring Broadband Australia report consistently shows that customers on 1Gbps plans receive median download speeds of around 750–850Mbps during peak hours — still impressive, but not the theoretical maximum. For 2Gbps services, the ACCC has not yet published statistically significant real-world benchmarks, but early adopter forums and ISP transparency reports suggest median speeds of 1.4–1.7Gbps.</p>
<p>Upload speeds tell a different story. FTTP services are typically asymmetric — a 2Gbps download plan often comes with 500Mbps or 1Gbps upload. For content creators, large file uploads, and remote server management, upload speed matters as much as download. Check your ISP's wholesale agreement with NBN Co to confirm the upload tier included in your plan.</p>
<p>Latency is arguably more important than raw speed for most interactive applications. Gaming, video calls, and real-time collaboration tools are latency-sensitive. NBN FTTP delivers median latencies of 8–12ms, compared to 20–35ms for cable (HFC) and 150–600ms for satellite. No amount of bandwidth compensates for high latency in interactive applications.</p>
<h2>The Router Bottleneck Most People Ignore</h2>
<p>Even if you subscribe to 2Gbps internet, your Wi-Fi router becomes the limiting factor for wireless devices. Standard Wi-Fi 5 (802.11ac) routers struggle to deliver more than 600–900Mbps to a single device. You need a Wi-Fi 6 or Wi-Fi 6E router to approach gigabit speeds wirelessly, and even then, real-world wireless throughput depends on signal strength, interference, and the capabilities of each connected device.</p>
<p>For wired connections — desktop computers, gaming consoles, smart TVs, network-attached storage — you need a router with 2.5G or 10G Ethernet ports to fully utilise a 2Gbps WAN connection. Most consumer routers sold in 2024 and earlier have only 1Gbps ports, creating a hard cap on wired throughput. Upgrading to a router with multi-gigabit ports typically adds $200–$500 to your setup cost.</p>
<p>Practical recommendation: if you have fewer than 10 heavy users in your home and don't run commercial-grade applications, 1Gbps NBN delivers effectively unlimited bandwidth for domestic use. The 2Gbps premium is currently justified mainly for home businesses, power users who routinely max out a 1Gbps connection, or technology enthusiasts who want future-proofing.</p>
"""

PATCHES['loyalty-tax-2026'] = """
<h2>The Compounding Effect: How Loyalty Tax Grows Over Years</h2>
<p>The loyalty tax doesn't just cost you money in a single year — it compounds. An energy customer who pays $200 more per year than the market rate loses $200 in year one. If they remain with the same provider for five years and rates rise by 3% annually, they pay not just $200 per year but an increasing margin on an increasing base rate. Over five years, the total loyalty premium can reach $1,200–$1,500.</p>
<p>Telecommunications customers face a similar dynamic. Internet prices are declining industry-wide, but loyal customers often stay on older, more expensive plans while new customers receive current promotional rates. An NBN customer who signed up in 2019 and hasn't reviewed their plan may be paying $99/month for 100Mbps while new customers receive the same speed for $69/month — a $360 annual loyalty penalty.</p>
<p>The most effective counter-strategy is calendar-based review rather than trigger-based review. Set a recurring annual reminder — the same week each year — to check competing offers across all your utilities. Even spending 30 minutes annually can recover $500–$1,500 in loyalty premiums. Some financial advisors now include utility plan reviews in annual financial health check-ups for exactly this reason.</p>
<h2>How to Negotiate Without Switching: Retention Offers</h2>
<p>If you prefer not to switch providers — perhaps because you're mid-contract, or because the switching process feels burdensome — retention teams can often match or approach competitive market offers. The key is to call with a specific competing offer in hand, not just a vague complaint about price.</p>
<p>Energy retailers' retention teams typically have authority to apply bill credits of $50–$150, upgrade you to a better market offer, or lock in a guaranteed discount rate for 12 months. Telecommunications companies can often apply account credits, upgrade your speed tier, or add extras like streaming subscriptions. The success rate of retention calls is substantially higher when you have a competing quote ready to reference and communicate genuine willingness to switch.</p>
"""

PATCHES['smart-meter-2026'] = """
<h2>Protecting Your Privacy With a Smart Meter</h2>
<p>Smart meters collect granular consumption data — in some cases at 15-minute or 30-minute intervals — which raises legitimate privacy considerations. Your energy retailer and distributor can potentially infer household occupancy patterns, appliance usage, and even behavioural habits from detailed interval data. Australian privacy legislation requires retailers to handle this data according to their published privacy policy, but policies vary in how long data is retained and with whom it is shared.</p>
<p>You have the right to request that your retailer limit data sharing with third parties for marketing purposes. Review your retailer's privacy policy before enabling detailed analytics features in their app, and opt out of any data-sharing arrangements you're uncomfortable with. The core functionality — billing and real-time monitoring — does not require sharing with third parties.</p>
<p>For most households, the financial benefits of a smart meter far outweigh the privacy considerations. But if you work from home, have vulnerable household members, or have specific security concerns, it is worth understanding what data is collected and how it's used before enabling all available features.</p>
"""

PATCHES['compare-energy-nsw-2026'] = """
<h2>Reading the Small Print: Contract Terms That Can Cost You</h2>
<p>Beyond the headline rate, several contract terms determine the true cost of an energy plan in NSW. Exit fees on fixed-rate contracts can reach $60–$150, making it expensive to switch if a better deal emerges mid-contract. Always ask: what is the exit fee, and does the rate lock apply to both supply charges and usage charges or only to one?</p>
<p>Conditional discounts remain common in NSW despite regulatory pressure. A "15% discount" that requires paperless billing, on-time payment, and direct debit effectively charges full tariff to anyone who misses even one payment. Calculate the rate you'd pay without the discount before committing — some unconditional plans are cheaper than discounted plans when you account for the risk of losing the discount.</p>
<p>NSW residents on the Energy Accounts Payment Assistance (EAPA) scheme should confirm with their new retailer that the scheme vouchers are accepted before switching. Most licensed retailers accept EAPA, but confirming upfront prevents complications at voucher redemption time.</p>
"""

PATCHES['cheapest-electricity-sydney'] = """
<h2>Sydney's Network Zones: Why Your Suburb Determines Your Bill</h2>
<p>Sydney's electricity network is divided into distribution zones served by Ausgrid (inner suburbs, eastern Sydney, north shore) and Endeavour Energy (western Sydney, southern highlands, Blue Mountains). Your distributor is determined by your address and cannot be changed by switching retailers. However, distribution charges — which make up roughly 40% of your electricity bill — differ between zones.</p>
<p>Ausgrid's network charges are typically slightly lower than Endeavour Energy's for residential customers, reflecting the denser urban network and higher asset utilisation. If you live in western Sydney and notice your bill is higher than friends in the inner suburbs, part of the difference is structural — not just your retailer's pricing.</p>
<p>Peak demand charges have been introduced for some residential customers in both zones. If your meter supports interval data, some retailers offer demand tariffs that charge based on your highest 30-minute consumption period each month, rather than a flat per-kWh rate. These tariffs can dramatically reduce bills for households that can shift major appliance use away from the 3–9pm evening peak.</p>
<h2>Energy Rebates Available to Sydney Households in 2026</h2>
<p>Sydney households can access multiple rebate programs that significantly reduce effective electricity costs. The NSW Energy Bill Relief program provides $250 per quarter to eligible households including pensioners, low-income earners, and medical support recipients. This translates to $1,000 per year in direct bill reduction — enough to offset several hundred dollars of annual usage charges.</p>
<p>The Low Income Household Rebate applies automatically to eligible concession card holders and provides an additional $285 per year. Self-funded retirees holding a Commonwealth Seniors Health Card are eligible. The Family Energy Rebate provides $180 per year for families receiving certain Family Tax Benefit payments.</p>
<p>Life Support Equipment Rebate applies to households with registered medical equipment like oxygen concentrators, dialysis machines, or home ventilators. The rebate amount varies by equipment type and usage. Eligible equipment must be registered with your distributor — contact Ausgrid or Endeavour Energy directly to register, as the rebate cannot be applied retrospectively in most cases.</p>
<h2>Comparing Retailers in Sydney: Beyond the Rate Card</h2>
<p>When comparing electricity retailers in Sydney, the headline rate comparison is just the starting point. Customer service quality, billing accuracy, and complaint handling vary significantly. The Australian Energy Regulator's annual Retail Energy Market performance report tracks complaint rates, billing disputes, and disconnection rates by retailer — it's worth reading before committing to an unfamiliar provider.</p>
<p>AGL, Origin Energy, and EnergyAustralia collectively serve most Sydney households. All three have comparable pricing with slight variations depending on your usage profile and whether you have solar. Smaller retailers like Tango Energy, Dodo Power & Gas, and Energy Locals have been consistently competitive on price in NSW and often rank highly on customer satisfaction surveys.</p>
<p>Green power options are widely available in Sydney. GreenPower accreditation means your retailer purchases renewable energy certificates equivalent to your consumption. Prices vary, but the premium for 100% GreenPower is typically $100–$200 per year for an average household. Some retailers include 20% GreenPower in standard plans at no extra cost — worth checking if environmental credentials matter to you.</p>
<h2>How to Switch Electricity Providers in Sydney: Step-by-Step</h2>
<p>Switching electricity providers in Sydney is a straightforward process that takes 5–10 minutes online. You'll need your current bill or NMI (National Meter Identifier — a 10 or 11 digit number usually found on the front of your bill). The NMI identifies your connection point on the network and ensures your new provider connects to the right meter.</p>
<p>Once you've chosen a new plan and signed up online or by phone, your new retailer handles the transfer process. There is no interruption to electricity supply — the switch happens at the billing level, not the physical network level. Transfer cooling-off periods typically run 10 business days, during which you can cancel without penalty if you change your mind.</p>
<p>Bills from your old retailer for the period before the transfer date will arrive in the normal billing cycle. Ensure your direct debit details are current with your old retailer to avoid final bill payment issues. Your new retailer will begin billing from the transfer date, and your first bill will typically cover 2–3 months as the billing cycle establishes.</p>
"""

PATCHES['agl-vs-origin-energy'] = """
<h2>AGL vs Origin: Solar and Battery Offerings Compared</h2>
<p>For solar households, AGL and Origin have developed quite different approaches to the energy ecosystem. AGL's Solar Savers plan bundles a competitive feed-in tariff with usage rate discounts for solar customers. Their AGL Solar Command product lets solar households participate in their virtual power plant when they add a compatible battery, earning additional payments for exporting stored energy during peak demand periods.</p>
<p>Origin's Solar Boost plan similarly offers enhanced feed-in tariffs for customers with solar. Origin has invested heavily in their Loop app, which displays real-time solar generation, grid import/export, and battery state-of-charge data for supported systems. Origin's VPP operates in South Australia and parts of Victoria, with national expansion planned through 2026.</p>
<p>Feed-in tariff rates fluctuate and both retailers adjust them periodically. As of early 2026, AGL's standard FiT sits around 5–7c/kWh depending on state, while Origin's comparable rate is similar. Neither matches the premium FiTs offered by specialist retailers like Energy Locals or Amber Electric, which use real-time wholesale pricing that can reach 20–30c/kWh during afternoon peak periods when solar is generating at maximum output.</p>
<h2>Business Energy: AGL vs Origin for SMEs</h2>
<p>Small business owners often ask whether AGL or Origin is better for their commercial premises. Both retailers have dedicated business divisions with tailored plans for small to medium enterprises. AGL's Business Energy team has a strong presence in NSW, Victoria, and Queensland. Origin's business division tends to offer more flexible contract terms for SMEs, including month-to-month options without exit fees.</p>
<p>For businesses consuming more than 100MWh per year, both AGL and Origin typically move to individually negotiated contracts rather than published tariffs. At this scale, an independent energy broker can add value by tendering to multiple retailers simultaneously and negotiating terms that a direct approach may not achieve.</p>
<p>Demand charges apply to many commercial tariffs and can represent 20–40% of a business energy bill. Origin's online comparison tools do a better job of explaining demand charge structures to small business owners unfamiliar with the concept. AGL's business portal provides more granular historical consumption data, which is valuable for identifying demand reduction opportunities.</p>
<h2>Complaint Handling and Customer Service: Independent Data</h2>
<p>Australian Energy Regulator data for 2024–25 shows both AGL and Origin receiving complaint volumes broadly proportional to their market share. AGL's complaint-to-customer ratio has improved year-on-year following a significant customer service investment in 2023–24. Origin's complaint rate remains slightly above the industry median, largely driven by billing complexity issues related to their solar and battery product suite.</p>
<p>The Energy and Water Ombudsman (EWOV in Victoria, EWON in NSW, EWO in other states) handles escalated disputes that retailers cannot resolve. Both AGL and Origin comply with ombudsman decisions within required timeframes. If you have a billing dispute that your retailer cannot resolve to your satisfaction, lodging an ombudsman complaint is free and typically produces a resolution within 4–8 weeks.</p>
"""

PATCHES['how-to-switch-electricity'] = """
<h2>What Happens to Your Old Account After Switching</h2>
<p>A common source of confusion is what happens to your old electricity account after you've switched to a new provider. Your old retailer will send a final bill covering the period from your last regular bill date to the transfer date. This final bill is calculated from a meter read — either an actual read by your distributor at the time of transfer, or an estimate if an actual read isn't taken.</p>
<p>If your old retailer holds a security deposit — common for customers who were on a prepayment plan or had a poor payment history — this should be refunded within 30 days of your final bill being paid. If you have a credit balance (for example, from overpaying a bill or receiving a large concession payment), this too should be refunded or credited to your final bill.</p>
<p>Cancel any direct debits associated with your old account once the final bill is settled. Leaving an old direct debit active is a common source of duplicate billing complaints. Similarly, update your records if your electricity costs are claimable as tax deductions — your new retailer will issue bills in their own format, and the billing cycle may not align with your financial year end.</p>
<h2>Switching When You Have Solar</h2>
<p>Switching retailers when you have a solar system requires a little more attention than a standard electricity transfer. Your feed-in tariff rate — what you're paid for excess solar exported to the grid — is not locked in by your current contract unless you have a specific solar FiT guarantee in writing. Switching to a new retailer resets your FiT to whatever rate the new retailer offers.</p>
<p>Some older customers have grandfathered FiT rates from state government premium schemes that were closed to new entrants years ago. If you're on a grandfathered premium FiT (common in Victoria and NSW for systems installed before 2012), switching retailers will permanently end that entitlement. The premium rate may be worth keeping even if your usage rate is slightly higher than competitors offer.</p>
<p>Before switching, calculate the annual value of your current FiT. For example, if you export 2,000 kWh per year and receive 6c/kWh, your FiT value is $120/year. If your new retailer offers only 4c/kWh but saves you $180/year on usage charges, you're still $60/year better off switching. Run the full numbers, not just the usage rate comparison.</p>
<h2>Switching Gas at the Same Time: Bundle Considerations</h2>
<p>If you have both electricity and gas accounts, you can switch them independently or together. Bundling electricity and gas with a single retailer sometimes unlocks additional discounts — AGL, Origin, and EnergyAustralia all offer dual-fuel discounts of 5–15% on one or both services when you hold both accounts with them.</p>
<p>However, the best electricity deal and the best gas deal may come from different retailers. Run separate comparisons for electricity and gas on the AER's Energy Made Easy portal, then compare the best individual deals against the best available bundle. In many cases, separate deals with different retailers beat the bundle by $100–$250 per year, particularly for households with modest gas usage.</p>
"""

PATCHES['electricity-bill-too-high'] = """
<h2>When to Escalate: Disputing an Unusual Bill</h2>
<p>If your electricity bill spikes unexpectedly and you've ruled out equipment and usage changes, you may have grounds to dispute the bill. Common causes of unexpectedly high estimated bills include a faulty meter read, an estimated bill that overestimated actual consumption, or a billing system error. Request an actual meter read if you've received estimated bills for more than two consecutive periods.</p>
<p>Under the National Energy Customer Framework, you have the right to request a meter test if you believe your meter is faulty. Your distributor must conduct the test, typically within 5 business days. If the meter tests as faulty, the distributor must provide a revised bill based on the best available estimate of actual consumption. If the meter is accurate, you may be charged a meter test fee of $50–$150.</p>
<p>Contact your retailer's billing dispute team before escalating to the Energy Ombudsman. Most billing disputes resolve at the retailer level within 5–10 business days. If you're not satisfied with the retailer's response, lodging an ombudsman complaint is free and pauses any debt collection action while the dispute is investigated.</p>
"""

PATCHES['vic-electricity-compare-2026'] = """
<h2>Victoria's Unique Energy Market: What Sets It Apart</h2>
<p>Victoria has the most competitive retail electricity market in Australia, with over 20 active retailers serving residential customers. This competition, combined with the Victorian Default Offer (VDO) as a regulated reference price, creates genuine price pressure that benefits consumers who compare plans regularly.</p>
<p>The VDO is set annually by the Essential Services Commission of Victoria and represents the maximum price an electricity retailer can charge a residential customer on a standing offer. Market offers — the competitive plans advertised by retailers — typically range from 5% to 30% below the VDO for customers who actively compare. The difference between paying VDO and taking the best available market offer can reach $400–$600 per year for an average Victorian household.</p>
<p>Victoria's smart meter rollout, completed by 2014, gives Victorian consumers more options than residents of most other states. Time-of-use tariffs, demand tariffs, and real-time pricing products (like Amber Electric's wholesale pricing) are all available to Victorian households with compatible meters, which is the overwhelming majority.</p>
<h2>Top Energy Retailers in Victoria: 2026 Rankings</h2>
<p>Comparing Victorian electricity retailers across price, customer service, and plan flexibility reveals a diverse competitive landscape. Tango Energy and Sumo Power consistently offer below-market rates for flat-rate plans. AGL and Origin compete strongly on solar-specific products. Energy Locals and Amber Electric appeal to tech-savvy customers comfortable with dynamic pricing.</p>
<p>Essential Energy's Cheaper Home Energy comparison tool (part of the Victorian Government's Better Bills initiative) allows consumers to upload their smart meter data and see exactly how much they would pay across all available plans — not just estimated comparisons based on average consumption. This tool is unique to Victoria and provides the most accurate comparison available anywhere in Australia.</p>
<p>For renters, it's worth confirming that your landlord's choice of embedded network or meter configuration doesn't lock you into a specific retailer. While the National Energy Retail Law requires on-selling to comply with price caps, some older embedded network arrangements predate current regulations. Contact the Essential Services Commission if you believe you're being charged above the VDO cap.</p>
<h2>Victorian Solar Feed-In Tariffs: State of the Market</h2>
<p>Victoria's Minimum FiT, set by the Essential Services Commission, applies as a floor under which no retailer can pay for solar exports. In 2025–26, the Minimum FiT rate is 4.9c/kWh. Many retailers exceed this floor — standard market FiTs range from 6c to 10c/kWh, and peak-period FiTs through dynamic pricing products can reach 20c+ during afternoon peak periods.</p>
<p>The Solar Homes Program provides rebates and interest-free loans to eligible Victorian households for solar panel installation and battery storage. Rebates of up to $1,400 for solar panels and $8,800 for batteries remain available subject to program funding. Applications are processed through Solar Victoria — approval can take several weeks during high-demand periods.</p>
<p>Households considering both solar and a battery should model the combined economics carefully. In Victoria, with competitive FiTs and strong daytime solar generation, the payback period for panels alone is typically 3–5 years. Adding a battery extends the payback period to 8–12 years depending on battery cost, usage profile, and whether you participate in a VPP. The economics improve meaningfully if you qualify for the Solar Homes rebate.</p>
<h2>Regional Victoria: Different Networks, Different Prices</h2>
<p>Distribution network charges in regional Victoria differ from metropolitan Melbourne. PowerCor serves central and northwest Victoria, CitiPower covers inner Melbourne, United Energy covers the southeast, and AusNet Services covers the east and northeast including alpine regions. AusNet's network charges are the highest in Victoria, reflecting the cost of maintaining long-distance transmission lines through difficult terrain.</p>
<p>Regional Victorian customers often pay $100–$200 more per year in network charges than equivalent Melbourne consumers, regardless of which retailer they choose. This structural cost difference is worth acknowledging when comparing bills with Melbourne-based friends or family. The retailer comparison process remains the same — it's still worth finding the best available market offer — but expectations about absolute bill levels should account for network zone differences.</p>
"""

PATCHES['melbourne-cheapest-electricity-2026'] = """
<h2>Melbourne's Smart Meter Advantage: Time-of-Use Made Easy</h2>
<p>Because all Melbourne homes have had smart meters since 2014, every household can immediately access time-of-use tariffs without a meter upgrade. This gives Melbourne consumers options unavailable in most other Australian cities. Off-peak rates from retailers like Tango Energy and AGL can be as low as 12–18c/kWh between 10pm and 7am, compared to peak rates of 28–40c/kWh during the 3–9pm evening peak window.</p>
<p>The catch is behaviour change. Time-of-use tariffs only save money if you can genuinely shift discretionary consumption — dishwashers, washing machines, EV charging, pool pumps — away from the peak window. Households that run appliances whenever convenient, including during the 3–9pm peak, can pay more on a TOU tariff than on a flat-rate plan. Use the Essential Services Commission's comparison tool to model your actual consumption data before switching tariff types.</p>
<p>Demand tariffs are a third option, available from some Melbourne retailers including AGL's Savers Plan. Instead of charging per-kWh during peak periods, demand tariffs charge based on your highest single 30-minute demand reading during the month. For households with controllable peak demand — for example, those with smart home systems that can automatically limit simultaneous appliance use — demand tariffs can produce the lowest bills of all tariff types.</p>
<h2>Melbourne Concessions and Rebates: Full List for 2026</h2>
<p>Melbourne households can access several concession programs that substantially reduce effective electricity costs. The Annual Electricity Concession provides eligible concession card holders with 17.5% off electricity usage and supply charges, capped at a maximum annual rebate. The Winter Gas Concession and the Controlled Load Reduction benefit also apply to eligible households.</p>
<p>The Victorian Energy Upgrades (VEU) program provides subsidised or free energy efficiency improvements — including LED lighting, insulation, draught sealing, and efficient appliance replacement — to Victorian households and businesses. Accredited providers install upgrades at reduced cost, funded by Victorian Energy Efficiency Certificates (VEECs). Contact Energy Saver (the Victorian Government energy efficiency program) to find accredited providers offering free upgrades in your Melbourne suburb.</p>
"""

PATCHES['agl-vs-energyaustralia-2026'] = """
<h2>AGL vs EnergyAustralia: Contract Flexibility Compared</h2>
<p>Contract flexibility matters if you anticipate life changes — moving house, installing solar, or wanting to switch again if a better deal emerges. AGL's market offers typically operate on a no-lock-in basis for residential customers, with the rate structure guaranteed for a set period (usually 12–24 months) but no exit fee if you leave early. This gives AGL customers genuine freedom to respond to market changes.</p>
<p>EnergyAustralia also offers no-exit-fee market contracts for most residential plans. Their fixed-rate products — where both supply charge and usage charge are locked for the contract period — carry exit fees of $50–$100, but provide certainty against rate increases. In a rising wholesale electricity market, a fixed-rate plan locks in today's rates and provides budgetary certainty.</p>
<p>For customers who value simplicity, EnergyAustralia's online account management system has historically received higher usability scores than AGL's platform. The MyAccount portal makes bill splitting, payment scheduling, and consumption monitoring straightforward. AGL's app has improved significantly following a major redesign in 2024–25 and now competes favourably on functionality.</p>
<h2>AGL vs EnergyAustralia for Renters</h2>
<p>Renters have the same switching rights as homeowners in Australia — you do not need landlord permission to change electricity retailers, as long as you're not in an embedded network arrangement. Both AGL and EnergyAustralia offer flexible payment options suitable for renters, including weekly and fortnightly billing to align with rental payment cycles.</p>
<p>Bond-free connection is available from both retailers for most residential connections. If your previous tenancy had outstanding debts with either retailer, you may be asked to provide a security deposit for a new connection — typically equal to the estimated value of two billing cycles. This deposit must be returned within 10 business days of your final bill being paid.</p>
<p>Moving house mid-contract can complicate billing. If your new property is serviced by a different distributor network, your retailer may need to set up a new account even if you're staying with the same provider. Always notify your retailer at least 3 business days before your move date to avoid connection delays at your new property.</p>
<h2>Green Energy Options: AGL vs EnergyAustralia</h2>
<p>Both retailers offer GreenPower accredited plans that source renewable energy certificates equivalent to your consumption. AGL's Solar and Wind GreenPower plan is one of Australia's most established green tariffs, with 100% GreenPower certification available for approximately $100–$180 per year premium over their standard rate.</p>
<p>EnergyAustralia's GreenPower options range from 10% to 100% coverage. Their carbon neutral certified plans include both GreenPower certificates and additional carbon offsets. For households wanting to minimise their environmental footprint without installing their own solar, GreenPower from either retailer is a credible and independently audited option.</p>
"""

PATCHES['solar-fit-australia-2026'] = """
<h2>Maximising Your Feed-In Tariff: Practical Strategies</h2>
<p>The feed-in tariff you receive is one factor in solar economics — but the rate you're paid matters less than the proportion of solar generation you consume yourself. Self-consumption of solar power displaces grid electricity at retail rates (currently 25–45c/kWh), while grid export earns only 4–15c/kWh. The arithmetic strongly favours consuming your own solar over exporting it.</p>
<p>Strategies to increase self-consumption include running dishwashers, washing machines, and dryers during peak solar generation (typically 10am–3pm), scheduling pool pump and hot water system operation to daylight hours, and — for those with electric vehicles — charging the vehicle during the middle of the day. These behavioural changes can increase self-consumption from 30–40% of total generation to 50–70%, substantially improving the financial return of your solar investment.</p>
<p>A battery storage system is the most effective technical solution for maximising self-consumption. Excess solar generation charges the battery during the day; the stored energy is discharged during the evening peak when grid electricity is most expensive. A well-sized battery can raise self-consumption to 80–90% of total generation, although the economics of adding a battery still depend heavily on battery cost, your usage profile, and available rebates.</p>
<h2>State-by-State FiT Summary: Quick Reference Guide</h2>
<p>Minimum feed-in tariff rates vary by state and are reviewed annually. Victoria's Minimum FiT (set by the Essential Services Commission) is 4.9c/kWh for 2025–26, with market offers frequently paying 6–10c/kWh. New South Wales has no regulated minimum, but competition among retailers keeps most FiT rates in the 4–8c/kWh range. Queensland's Ergon and Energex networks pay a regulated solar bonus of 6.348c/kWh to eligible customers. South Australia has no mandatory minimum, and FiT rates from major retailers typically sit between 3–7c/kWh. Western Australia's Distributed Energy Buyback Scheme pays 10c/kWh peak and 3c/kWh off-peak for systems under 5kW — among the most structured FiT schemes in the country.</p>
<p>ACT households benefit from the ActewAGL Solar Buyback scheme which provides competitive rates, while Tasmania's TasNetworks FiT sits at 8.338c/kWh under the regulated tariff. Northern Territory customers are served by Territory Generation and generally receive lower FiT rates reflecting the isolated grid structure.</p>
<p>Regardless of state, dynamic pricing products from retailers like Amber Electric can dramatically outperform standard FiTs by paying wholesale spot prices for solar exports during peak demand periods. During high-demand summer afternoons, wholesale prices can spike to $0.30–$3.00/kWh, dwarfing standard FiT rates. The trade-off is billing volatility — import prices also reflect spot rates and can be high during the same peak periods.</p>
"""

PATCHES['flat-rate-vs-tou-2026'] = """
<h2>Demand Tariffs: A Third Option Worth Considering</h2>
<p>Beyond flat-rate and time-of-use tariffs, a third billing model — demand tariffs — is worth understanding for households with variable consumption patterns. Demand tariffs charge a fixed monthly fee based on your peak demand reading (the highest 30-minute average power draw recorded during the billing period) rather than or in addition to per-kWh usage charges.</p>
<p>For households where peak demand events are occasional and manageable — for example, one particularly heavy usage evening per month — demand tariffs can produce bills substantially lower than both flat-rate and TOU alternatives. A household that routinely limits simultaneous appliance use (never running the oven, dishwasher, and electric vehicle charger at the same time) may find a demand tariff rewards their behaviour with significant savings.</p>
<p>The risk is that a single unavoidable high-demand event — a hot day requiring sustained air conditioning, or a guest stay that strains the household's electrical load — can set a high monthly demand charge that persists for the entire billing period. Demand tariffs suit households with smart home automation capable of automatically limiting load during potential peak periods, not those who want a set-and-forget billing arrangement.</p>
"""

PATCHES['qld-electricity-2026'] = """
<h2>Queensland's Unique Retail Structure: Ergon, Energex, and Market Retailers</h2>
<p>Queensland's electricity retail market is structured differently from southern states. In southeast Queensland (the Energex network area), a fully competitive retail market operates with 15+ active retailers competing for customers. Outside southeast Queensland — in the Ergon Energy network area covering regional and remote Queensland — Ergon Energy Retail is the default provider and competition is more limited.</p>
<p>The Uniform Tariff Policy means residential customers across Queensland pay the same regulated tariff rate regardless of whether they're in Brisbane or Cairns, despite vastly different network delivery costs. This cross-subsidy is funded by the Queensland Government and means rural Queenslanders aren't penalised with higher rates for their more expensive network supply. However, it also means market offer discounts may be smaller or less available outside southeast Queensland.</p>
<p>In southeast Queensland, the Queensland Competition Authority (QCA) sets the notified prices that serve as the regulated reference rate. Market offers from retailers like AGL, Origin, EnergyAustralia, Alinta Energy, and smaller retailers like Tango and Sumo typically undercut the QCA notified price by 10–25% for customers who compare and switch.</p>
<h2>Queensland Solar Incentives: FiT Rates and VPP Options</h2>
<p>Queensland has historically had strong solar uptake, driven by high sunshine hours and state government incentive programs. The Solar Bonus Scheme (now closed to new entrants) paid eligible customers 44c/kWh for solar exports — a legacy rate that grandfathered participants continue to benefit from. If you installed solar before 2012 and registered under the scheme, this rate should continue until 2028 when the scheme ends.</p>
<p>New solar installations in Queensland receive market FiT rates currently ranging from 6–12c/kWh depending on retailer. Ergon and Energex networks have been proactive about managing solar export constraints during midday hours — some feeders in high-solar suburbs have soft limits on export that can reduce the effective FiT value during peak generation periods.</p>
<p>Virtual power plant programs are growing in Queensland. AGL's VPP in southeast Queensland and Origin's similar program have enrolled thousands of battery-equipped homes. The Queensland Government's Battery Booster rebate of up to $4,000 for eligible households has accelerated battery adoption, increasing the pool of VPP-eligible homes substantially.</p>
<h2>Cost of Living Support: Queensland Energy Bill Rebates</h2>
<p>Queensland's electricity bill relief package for 2025–26 includes a $325 credit applied automatically to residential electricity accounts through the relevant distribution network. This credit appears on bills from eligible Queensland electricity accounts without the need to apply. Additional concessions are available for Queensland Concession Card holders, including the Electricity Rebate of $372.45 per year and the Reticulated Natural Gas Rebate.</p>
<p>Medical cooling concession is available for Queensland households where a resident has a medical condition requiring indoor temperature management. The concession applies during the cooling season and provides a per-kWh rebate on electricity used for air conditioning. Eligible conditions include multiple sclerosis, severe heart failure, and other heat-sensitive medical conditions. Apply through your electricity retailer with supporting medical documentation.</p>
<p>Life support customers in Queensland must register their equipment with their distributor (Energex or Ergon Energy) to access priority restoration services during outages and advance notice of planned maintenance. Registration is free and can be completed online. Contact your retailer if you're unsure whether your household qualifies — the definition of life support equipment is broader than most people assume and includes some respiratory support devices and home dialysis equipment.</p>
"""

PATCHES['mobile-plans-compare-2026'] = """
<h2>MVNO vs Big Three: The Hidden Network Connection</h2>
<p>Mobile virtual network operators (MVNOs) don't own their own towers — they lease capacity from Telstra, Optus, or Vodafone and resell it under their own brand. This means an MVNO on the Telstra network offers essentially the same geographic coverage as Telstra itself, but typically at 30–50% lower prices. Understanding which network an MVNO uses is the single most important factor in evaluating whether a cheaper plan represents genuine value.</p>
<p>Telstra-backed MVNOs include Belong, Boost Mobile, and Aldi Mobile. These offer Telstra's extensive 4G/5G coverage — covering 99.5% of the Australian population — at substantially reduced prices. Optus-backed MVNOs include Amaysim, Coles Mobile, and Woolworths Mobile. Optus's network covers 98.5% of the population and is the preferred choice in urban areas where Optus's 5G deployment is ahead of Telstra in some suburbs.</p>
<p>Vodafone-backed MVNOs are fewer but include TPG Mobile. Vodafone's network coverage has improved significantly since the TPG merger, but remains below Telstra and Optus particularly in regional areas. For customers in major metropolitan areas, Vodafone network coverage is generally sufficient, and the price differential can be compelling.</p>
<h2>5G Plans: When Does the Premium Make Sense?</h2>
<p>5G plan premiums have compressed significantly as 5G becomes mainstream. In 2026, many mid-range plans from major carriers and MVNOs include 5G access at no additional cost over the equivalent 4G plan. The decision is less about paying for 5G than ensuring your phone supports the correct 5G spectrum bands used in your area.</p>
<p>Australia has deployed 5G on both sub-6GHz frequencies (providing broader coverage at moderate speeds) and mmWave (providing very high speeds in dense urban locations but limited range). Most 5G phones sold in Australia support sub-6GHz 5G. Only high-end flagship phones support mmWave 5G, which is currently deployed only in select CBD locations in Sydney, Melbourne, and Brisbane.</p>
<p>If you live or work in a 5G coverage area and your phone supports it, 5G can deliver download speeds of 200–800Mbps compared to 50–200Mbps on 4G LTE. The practical difference for most users is faster large file downloads and smoother streaming at 4K resolution on mobile. For everyday browsing, social media, and messaging, 4G LTE remains more than sufficient.</p>
<h2>International Roaming: Comparing the Major Carriers</h2>
<p>International travel plans vary significantly between carriers and can represent substantial costs for frequent travellers. Telstra's day pass roaming ($5/day in select countries) activates automatically and provides the same data allowance as your domestic plan while overseas. Origin Digital (formerly Circles.Life) and Moose Mobile offer more competitive long-term international roaming arrangements for frequent travellers.</p>
<p>For occasional overseas trips, buying a local SIM at your destination remains the most cost-effective option for data. Many Australian carriers' roaming rates, while improved from historical levels, still significantly exceed local SIM prices in popular destinations like Thailand, the UK, and Japan. An international eSIM from providers like Airalo or Nomad can provide affordable data roaming without a physical SIM swap.</p>
"""

PATCHES['nbn-vs-5g-internet-2026'] = """
<h2>Latency Comparison: Why It Matters for Your Use Case</h2>
<p>Raw speed is only one dimension of internet performance. Latency — the round-trip time for a data packet — affects interactive applications disproportionately. NBN FTTP and FTTC connections consistently achieve median latencies of 8–15ms to local servers. 5G home internet latency typically ranges from 15–40ms, with occasional spikes above 50ms during network congestion.</p>
<p>For gaming, the difference between 12ms and 35ms latency is meaningful in fast-paced competitive titles where reaction times matter. Most non-competitive gaming is comfortable at latencies below 50ms. For video calls — Teams, Zoom, FaceTime — the threshold for noticeable delay is around 150ms round-trip; both NBN and 5G home internet operate well below this level.</p>
<p>Jitter (variability in latency over time) is arguably more important than absolute latency for real-time applications. NBN fixed-line services generally exhibit lower jitter than wireless 5G services, which can experience brief latency spikes as cell towers manage competing devices. For voice-over-IP business telephony where consistent call quality is essential, fixed-line NBN remains the more reliable choice.</p>
<h2>Data Caps and Fair-Use Policies on 5G</h2>
<p>Most 5G home internet plans are marketed as "unlimited," but fair-use policies vary between providers and networks. Telstra's 5G home internet applies a fair-use clause that may result in speed management after sustained heavy usage periods. Optus's 5G home plan has a 1TB monthly inclusion before speeds are managed. TPG's 5G plans offer genuine unlimited data on eligible connections.</p>
<p>Heavy data users — households that stream 4K content on multiple TVs, download large game files, or work with large datasets — should investigate the specific fair-use policy of any 5G plan before signing up. A household using 2–3TB per month is at risk of speed management on plans that cap at 1TB or apply aggressive fair-use thresholds.</p>
<p>NBN plans increasingly offer unlimited data at all speed tiers. For high-data households, the certainty of a fixed-line unlimited NBN plan may outweigh the convenience of 5G home internet, even if the 5G plan is technically marketed as unlimited. Check independent forums and reviews for real-world data cap experiences before committing.</p>
"""

PATCHES['car-insurance-compare-2026'] = """
<h2>Telematics and Black Box Insurance: The New Frontier</h2>
<p>Usage-based insurance (UBI), also called telematics or black box insurance, represents a growing segment of the Australian car insurance market. Providers including Budget Direct, NRMA, and newer entrants like Stella Insurance offer policies that monitor driving behaviour through a smartphone app or plug-in device, then price premiums based on actual driving patterns rather than demographic proxies.</p>
<p>For low-mileage drivers, young drivers with demonstrably safe habits, or those who primarily drive in low-risk periods (daytime, weekdays), telematics policies can produce premiums 20–40% below standard market rates. The trade-off is ongoing monitoring and the discipline required to maintain safe driving scores. A period of driving in unfamiliar areas, at night, or in adverse weather can negatively affect your score and raise your renewal premium.</p>
<p>Pay-as-you-drive policies from providers like Budget Direct's Kilometre car insurance charge a base rate plus a per-kilometre rate. For vehicles driven under 10,000km per year — second cars, classic vehicles, or cars used primarily for local errands — pay-per-km policies can produce the lowest annual premiums available. Calculate your average annual kilometres before dismissing this option.</p>
<h2>When to Review Your Car Insurance: Trigger Events</h2>
<p>Many Australians renew car insurance automatically without review, missing the opportunity to reduce premiums or improve coverage. Several life events should trigger a proactive insurance review: moving to a new suburb (postcodes affect theft and accident risk ratings), changing your primary parking arrangement (street parking to secure garage substantially reduces premiums), buying or selling a vehicle, adding a driver to your household, or accumulating additional years of claim-free driving.</p>
<p>Claim-free bonus structures vary between insurers but typically reduce premiums by 5–10% per claim-free year, up to a maximum (often 60–65% total discount). If you've been claim-free for several years with your current insurer, confirm whether you receive maximum no-claim bonus or whether a competitor would give you the same or higher bonus, since some insurers cap the accrual faster.</p>
<p>At renewal time, compare at least three to four quotes from different insurers. Premiums for identical cover can vary by $300–$700 per year for common vehicles. The online comparison portals — iSelect, Compare the Market, and Canstar — provide quick multi-insurer quotes, but some major insurers including NRMA, AAMI, and RAC don't participate in comparison sites. Always include at least one direct quote from these providers in your comparison.</p>
"""

if __name__ == '__main__':
    with open('assets/data/blog_posts.json') as f:
        posts = json.load(f)
    updated = 0
    for post in posts:
        pid = post.get('id', '')
        if pid in PATCHES:
            post['content'] = post['content'] + PATCHES[pid]
            updated += 1
    with open('assets/data/blog_posts.json', 'w', encoding='utf-8') as f:
        json.dump(posts, f, indent=2, ensure_ascii=False)
    print(f'Patch 2 complete: {updated} articles extended.')
    # Quick word count check
    import re
    print('\nWord counts after patch 2:')
    for post in posts:
        pid = post.get('id','')
        if pid in PATCHES:
            content = post.get('content','')
            stripped = re.sub(r'<[^>]+>', ' ', content)
            stripped = re.sub(r'\s+', ' ', stripped).strip()
            wc = len(stripped.split()) if stripped else 0
            status = 'OK' if wc >= 2500 else f'FAIL ({2500-wc} short)'
            print(f'  {pid:45} {wc}w [{status}]')
